version: '3.8'

services:
  web:
    build: .
    image: r4y4n3/projeto_igreja-server
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:PTHHOstJuOVkPhtSIlfboNjVeWwyvNSa@postgres.railway.internal:5432/railway
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    secrets:
      - r4y4n3
      - Jr679832@

  db:
    image: postgres
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PTHHOstJuOVkPhtSIlfboNjVeWwyvNSa
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

secrets:
  dockerhub_username:
    external: true
  dockerhub_password:
    external: true
